src/OverwatchHeroBundle/Entity/Hero.php
<?php

namespace OverwatchHeroBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Hero
 *
 * @ORM\Table(name="hero")
 * @ORM\Entity(repositoryClass="OverwatchHeroBundle\Repository\HeroRepository")
 */
class Hero
{

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, unique=true)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity="CategoryBundle\Entity\Category", inversedBy="heroes")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id")
     */
    private $category;

    /**
     * @var text
     *
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    /**
    * @var array
    *
    *@ORM\OneToMany(targetEntity="UserBundle\Entity\Review", mappedBy="hero")
    *@ORM\JoinColumn(name="review_id", referencedColumnName="id")
    */
    private $reviews;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Hero
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

     /**
     * Set category
     *
     * @param string $category
     *
     * @return Hero
     */
    public function setCategory($category)
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Get Category
     *
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
      * Set reviews
      *
      * @param Review $reviews
      *
      * @return Hero
      */
     public function setReviews($reviews)
     {
         $this->reviews = $reviews;
 
         return $this;
     }

    /**
     * Get Reviews
     *
     * @return array
     */
    public function getReviews()
    {
        return $this->reviews;
    }

     public function getAverageRating(): float
     {
         $ratings = [];
         foreach ($this->getReviews() as $review) {
             $ratings[] = $review->getRate();
         }
         
         if (count($ratings) === 0) {
             return 0;
         }
         
         return round(array_sum($ratings) / count($ratings),2);
     }

     /**
     * Set description
     *
     * @param string $description
     *
     * @return Hero
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

     public function getImage()
    {
        $name = strtoupper($this->name);
        $name = str_replace(' ', '_', $name);
        
        return sprintf(
            'public/%s.png',
            $name
        );
    }

     public function getCapacity()
    {
        $name = strtoupper($this->name);
        $name = str_replace(' ', '_', $name);
        $src = sprintf('public/%scapacity.png',$name);
        if( file_exists($src) ){
        return $src;
    }
    
        else{
        return 'public/sadface.png';
        }
    }
}

src/OverwatchHeroBundle/Form/HeroType.php
<?php

namespace OverwatchHeroBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class HeroType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name')->add('category');
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'OverwatchHeroBundle\Entity\Hero'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'overwatchherobundle_hero';
    }


}

src/OverwatchHeroBundle/Controller/HeroController.php
<?php

namespace OverwatchHeroBundle\Controller;

use OverwatchHeroBundle\Entity\Hero;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use CategoryBundle\Entity\Category;

/**
 * Hero controller.
 *
 * @Route("admin/hero")
 */
class HeroController extends Controller
{
    /**
     * Lists all hero entities.
     *
     * @Route("/", name="admin_hero_index")
     * @Method("GET")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $heroes = $em->getRepository('OverwatchHeroBundle:Hero')->findAll();

        return $this->render('hero/index.html.twig', array(
            'heroes' => $heroes,
        ));
    }

    /**
     * Creates a new hero entity.
     *
     * @Route("/new", name="admin_hero_new")
     * @Method({"GET", "POST"})
     */
    public function newAction(Request $request)
    {
        $hero = new Hero();
        $form = $this->createForm('OverwatchHeroBundle\Form\HeroType', $hero);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($hero);
            $em->flush();

            return $this->redirectToRoute('admin_hero_show', array('id' => $hero->getId()));
        }

        return $this->render('hero/new.html.twig', array(
            'hero' => $hero,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a hero entity.
     *
     * @Route("/{id}", name="admin_hero_show")
     * @Method("GET")
     */
    public function showAction(Hero $hero)
    {
        $deleteForm = $this->createDeleteForm($hero);

        return $this->render('hero/show.html.twig', array(
            'hero' => $hero,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing hero entity.
     *
     * @Route("/{id}/edit", name="admin_hero_edit")
     * @Method({"GET", "POST"})
     */
    public function editAction(Request $request, Hero $hero)
    {
        $deleteForm = $this->createDeleteForm($hero);
        $editForm = $this->createForm('OverwatchHeroBundle\Form\HeroType', $hero);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_hero_edit', array('id' => $hero->getId()));
        }

        return $this->render('hero/edit.html.twig', array(
            'hero' => $hero,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a hero entity.
     *
     * @Route("/{id}", name="admin_hero_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, Hero $hero)
    {
        $form = $this->createDeleteForm($hero);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($hero);
            $em->flush();
        }

        return $this->redirectToRoute('admin_hero_index');
    }

    /**
     * Creates a form to delete a hero entity.
     *
     * @param Hero $hero The hero entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Hero $hero)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('admin_hero_delete', array('id' => $hero->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }
}

src/OverwatchHeroBundle/Resources/views/Hero/detail.html.twig
{% extends 'OverwatchHeroBundle:asset:layout.html.twig' %}

{% block title %}
	Détails du Héros
{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
            <div class="card borderCustom">
                        <div class="card-body">
                                    <img class="img-thumbnail float-right" src="{{ asset(hero.image) }}" />
            	            <h1>
                                                {{ hero.name }}
                                    </h1>
            	            <p>
                                                {{ hero.description }}
                                    </p>  
                                    <img class="{% if hero.capacity != 'public/sadface.png' %} capacity {% endif %}" src="{{ asset(hero.capacity) }}" />
                                    {% include "OverwatchHeroBundle:Comparator:heroversusdropdown.html.twig" %}
                        </div>
            </div>
            </br>
            <h2 class="center">Liste des avis</h2>
            <h4>Moyenne : {{ hero.averageRating }}</h4>  
            
            {% for review in hero.reviews %}
            <div class="card borderCustom">
                        <div class="card-body">
                                    <h4 class="card-title">{{ review.user.email }} a noté {{ review.rate }} / 10</h4>
                        </div>
                        
                        {% if review.comment %}
                                    <div class="card-body">
                                                <blockquote class="blockquote">
                                                <p class="mb-0">{{ review.comment }}</p>
                                                </blockquote>
                                    </div>
                        {% endif %}
            </div>
            {% endfor %}
 
            {% if review_form %}
            </br>
            <h2>Ajouter une note</h2>
            </br>
            <div class="card">
                        {% form_theme review_form 'formtheme.html.twig' %}
                        <div class="center">
                                    <label id="rangeValueDisplayed" value="0">0</label> / 10
                        </div>

                        {{ form(review_form) }}
            </div>
            {% endif %}

            {% if not is_granted('IS_AUTHENTICATED_FULLY') %}
                        <p> Pour laisser un avis, veuillez vous <a href="{{ path('login') }}">connecter</a> ou vous <a href="user_register">inscrire</a> :) </p>
            {% endif %}
            </br>
            <button type="button" class="btn btn-outline-primary">
                        <a id="classTest" href="{{ path('overwatch_list') }}">Retour à la liste</a>
            </button>
{% endblock %}
       